"""empty message

Revision ID: b6ef2df6aeda
Revises: 2453e8d22ac1
Create Date: 2021-02-26 00:07:42.269953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ef2df6aeda'
down_revision = '2453e8d22ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'users', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'uid')
    # ### end Alembic commands ###
